# Gradle Properties
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Loom version
loom_version=1.6.+

# Mod Properties
mod_version=2.0.0
maven_group=com.simonbaars
archives_base_name=instant-massive-structures

# Minecraft Properties
# Check https://fabricmc.net/develop/ for the latest versions
minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
loader_version=0.16.9

# Fabric API
fabric_version=0.107.0+1.21.1
